spring:
  # H2 ??
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: sdfghjkwertyuidcfghjkertyuifghjhhsthdtserfdrtyuhgyu
  key: jwt
  access-token-expiration-minutes: 10
  refresh-token-expiration-minutes: 180